name: "PEST"

on: [push, pull_request]

jobs:

  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: github_actions
          MYSQL_PASSWORD: github_secret
          MYSQL_DATABASE: github_actions
          MYSQL_ROOT_PASSWORD: github_secret
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prepare the environment
        run: cp .env.github .env
      - name: Set Composer config
        run: composer config disable-tls true
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
#      - name: compile assets
#        run: npm install && npm run prod
      - name: Generate key
        run: php artisan key:generate
      - name: Execute PEST
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: ./vendor/bin/pest --coverage
